import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Roboto_Slab } from "next/font/google";

import "./globals.css";



const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto_slab = Roboto_Slab({
  variable: "--font-geist-serif",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_slab.className} body`}
      >
        {children}
      </body>
    </html>
  );
}
